# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/g2_hdmi_datapath/Genesys2_hdmi_datapath/rtl/g2hdmi_xdc.xdc

# Block Designs: bd/g2_datapath/g2_datapath.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==g2_datapath || ORIG_REF_NAME==g2_datapath} -quiet] -quiet

# IP: bd/g2_datapath/ip/g2_datapath_clk_wiz_0_0/g2_datapath_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==g2_datapath_clk_wiz_0_0 || ORIG_REF_NAME==g2_datapath_clk_wiz_0_0} -quiet] -quiet

# IP: bd/g2_datapath/ip/g2_datapath_dvi2rgb_0_1/g2_datapath_dvi2rgb_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==g2_datapath_dvi2rgb_0_1 || ORIG_REF_NAME==g2_datapath_dvi2rgb_0_1} -quiet] -quiet

# IP: bd/g2_datapath/ip/g2_datapath_rgb2dvi_0_0/g2_datapath_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==g2_datapath_rgb2dvi_0_0 || ORIG_REF_NAME==g2_datapath_rgb2dvi_0_0} -quiet] -quiet

# XDC: e:/g2_hdmi_datapath/Genesys2_hdmi_datapath/prj/g2_hdmi_prj/g2_hdmi_prj.gen/sources_1/bd/g2_datapath/g2_datapath_ooc.xdc
